services:
  tive-bot:
    build: .
    container_name: tive-bot
    restart: always
    env_file:
      - .env
    volumes:
      # PERSISTENCIA: Los archivos subidos se guardan en tu PC real
      - ./servicio/verCertificado:/app/servicio/verCertificado
      - ./tarjeta:/app/tarjeta
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
