services:
  tive-bot:
    build: .
    container_name: tive-bot
    restart: always
    env_file:
      - .env
    volumes:
      # PERSISTENCIA REAL: Los datos viven en el disco duro del servidor, fuera de Easypanel
      - /root/backups_sunarp/certificados:/app/servicio/verCertificado
      - /root/backups_sunarp/logs:/app/logs
    environment:
      - NODE_ENV=production
